import uuid
import asyncio
import logging
from typing import Dict, Any, List, Optional

from core.planner import Planner
from core.reasoning_engine import ReasoningEngine
from core.reflection_engine import ReflectionEngine

from memory.short_term_memory import ShortTermMemory
from memory.episodic_memory import EpisodicMemory
from memory.vector_store import VectorStore

from security.policy_engine import PolicyEngine
from monitoring.logging import get_logger


class Orchestrator:
    """
    Central control unit responsible for coordinating
    planning, reasoning, execution, reflection, and memory.
    """

    def __init__(
        self,
        agents: Dict[str, Any],
        tools: Dict[str, Any],
        config: Dict[str, Any],
    ):

        self.logger = get_logger("orchestrator")

        self.agents = agents
        self.tools = tools
        self.config = config

        self.planner = Planner(config)
        self.reasoner = ReasoningEngine(config)
        self.reflector = ReflectionEngine(config)

        self.short_memory = ShortTermMemory()
        self.long_memory = VectorStore(config)
        self.episodic_memory = EpisodicMemory()

        self.policy_engine = PolicyEngine(config)

        self.active_tasks: Dict[str, Dict] = {}

        self.logger.info("Orchestrator initialized")

    async def handle_request(self, user_input: str) -> Dict[str, Any]:
        """
        Entry point for new user requests.
        """

        task_id = str(uuid.uuid4())

        self.logger.info(f"Received task {task_id}")

        task_context = {
            "task_id": task_id,
            "goal": user_input,
            "status": "created",
            "steps": [],
        }

        self.active_tasks[task_id] = task_context

        try:

            enriched_goal = await self._retrieve_context(user_input)

            plan = await self.planner.generate_plan(enriched_goal)

            result = await self._execute_plan(task_id, plan)

            reflection = await self.reflector.reflect(plan, result)

            await self._update_memory(user_input, plan, result, reflection)

            task_context["status"] = "completed"
            task_context["result"] = result

            return {
                "task_id": task_id,
                "status": "completed",
                "result": result,
            }

        except Exception as e:

            self.logger.error(f"Task {task_id} failed: {e}")

            task_context["status"] = "failed"

            return {
                "task_id": task_id,
                "status": "failed",
                "error": str(e),
            }

    async def _retrieve_context(self, goal: str) -> str:
        """
        Retrieve relevant memory context for reasoning.
        """

        self.logger.debug("Retrieving contextual memory")

        memories = self.long_memory.search(goal)

        context = "\n".join([m["content"] for m in memories])

        enriched_goal = f"""
Goal:
{goal}

Relevant Context:
{context}
"""

        return enriched_goal

    async def _execute_plan(
        self,
        task_id: str,
        plan: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """
        Execute steps generated by planner.
        """

        results = []

        for step in plan:

            action = step.get("action")
            agent_name = step.get("agent")

            if not self.policy_engine.is_allowed(action):
                raise PermissionError(f"Action not allowed: {action}")

            self.logger.info(f"Executing step: {action}")

            if agent_name and agent_name in self.agents:

                agent = self.agents[agent_name]

                result = await agent.execute(step)

            elif action in self.tools:

                tool = self.tools[action]

                result = await self._execute_tool(tool, step)

            else:

                result = await self.reasoner.reason(step)

            results.append(result)

            await self.short_memory.store(result)

        return {"steps": results}

    async def _execute_tool(self, tool, step: Dict[str, Any]) -> Any:
        """
        Execute a tool safely.
        """

        try:

            parameters = step.get("parameters", {})

            if asyncio.iscoroutinefunction(tool):

                result = await tool(**parameters)

            else:

                result = tool(**parameters)

            return result

        except Exception as e:

            self.logger.error(f"Tool execution failed: {e}")

            raise

    async def _update_memory(
        self,
        goal: str,
        plan: List[Dict],
        result: Dict,
        reflection: Dict,
    ):
        """
        Persist learning into memory systems.
        """

        memory_entry = {
            "goal": goal,
            "plan": plan,
            "result": result,
            "reflection": reflection,
        }

        self.episodic_memory.store(memory_entry)

        self.long_memory.add_document(
            content=str(memory_entry),
            metadata={"type": "task_record"},
        )

    async def run_background_tasks(self):
        """
        Optional autonomous agent loop.
        """

        self.logger.info("Starting background task loop")

        while True:

            try:

                scheduled_tasks = self._get_scheduled_tasks()

                for task in scheduled_tasks:

                    await self.handle_request(task["goal"])

                await asyncio.sleep(self.config.get("scheduler_interval", 60))

            except Exception as e:

                self.logger.error(f"Background task failure: {e}")

    def _get_scheduled_tasks(self) -> List[Dict]:
        """
        Retrieve autonomous scheduled tasks.
        """

        return []

    def get_status(self) -> Dict[str, Any]:
        """
        System health and active task state.
        """

        return {
            "active_tasks": len(self.active_tasks),
            "agents": list(self.agents.keys()),
            "tools": list(self.tools.keys()),
        }